/** Ações registradas em `user_audit_logs` — nunca inclui senha/token/cookie nos detalhes. */
export enum UserAuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  PERMISSIONS_CHANGED = 'PERMISSIONS_CHANGED',
  ACCOUNT_SCOPE_CHANGED = 'ACCOUNT_SCOPE_CHANGED',
}
